# Generated by Django 2.2.13 on 2021-06-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Phone')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='Name')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='ru', max_length=20, verbose_name='Language')),
                ('point', models.IntegerField(default=0, verbose_name='Point')),
            ],
        ),
    ]
