# Generated by Django 2.2.13 on 2021-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=25, unique=True, verbose_name='Number'),
        ),
    ]
