# Generated by Django 2.2.13 on 2021-06-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unp', models.CharField(max_length=30, verbose_name='UNP')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('legal_address', models.CharField(max_length=50, verbose_name='Legal address')),
                ('address_order', models.CharField(max_length=50, verbose_name='Delivery address')),
                ('contact_person', models.CharField(max_length=50, verbose_name='The contact person')),
                ('number', models.CharField(max_length=15, verbose_name='Number')),
                ('note', models.TextField(max_length=2000, verbose_name='Note')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('payment', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Card'), (2, 'Online')], verbose_name='Payment format')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Phone')),
                ('first_name', models.CharField(max_length=30, verbose_name='Name')),
                ('point', models.IntegerField(default=0, verbose_name='Point')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
