# Generated by Django 2.2.13 on 2021-07-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='point',
            new_name='points',
        ),
    ]
