# Generated by Django 2.2.13 on 2021-07-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_price_price'),
        ('clients', '0003_auto_20210611_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Price'),
            preserve_default=False,
        ),
    ]
