# Generated by Django 2.2.13 on 2021-06-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210522_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalUser',
        ),
    ]
