# Generated by Django 2.2.13 on 2021-05-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_legaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, verbose_name='Point'),
        ),
    ]
