# Generated by Django 2.2.13 on 2021-05-15 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('first_name', models.CharField(max_length=100, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('delivery_date', models.DateField(verbose_name='Delivery date')),
                ('delivery_time', models.SmallIntegerField(choices=[(0, '09-10'), (1, '10-11'), (2, '11-12'), (3, '12-13'), (4, '13-14'), (5, '14-15'), (6, '15-16'), (7, '16-17'), (8, '17-18'), (9, '18-18.30')], verbose_name='Delivery time')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('payment', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Card'), (2, 'Online')], verbose_name='Payment method')),
                ('status', models.BooleanField(default=0, verbose_name='Payment confirmed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='PageTextGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='Page name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Page text',
                'verbose_name_plural': 'Page texts',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('idChat', models.CharField(max_length=255, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Модератор',
                'verbose_name_plural': 'Модераторы',
            },
        ),
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('text_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='shop.PageTextGroup')),
            ],
            options={
                'verbose_name': 'Page text',
                'verbose_name_plural': 'Page texts',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'Small'), ('large', 'Large'), ('none', 'None')], max_length=100, verbose_name='Size')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Pizza', verbose_name='Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='LegalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('delivery_date', models.DateField(verbose_name='Delivery date')),
                ('delivery_time', models.SmallIntegerField(choices=[(0, '09-10'), (1, '10-11'), (2, '11-12'), (3, '12-13'), (4, '13-14'), (5, '14-15'), (6, '15-16'), (7, '16-17'), (8, '17-18'), (9, '18-18.30')], verbose_name='Delivery time')),
                ('legalClient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.LegalUser', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Юридический заказ',
                'verbose_name_plural': 'Юридические заказы',
            },
        ),
    ]
