# Generated by Django 2.2.5 on 2019-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Card'), (2, 'Online')], default=1, verbose_name='Payment method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Payment status'),
        ),
    ]
