# Generated by Django 2.2.5 on 2019-10-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191001_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Payment confirmed'),
        ),
    ]
