# Generated by Django 2.2.5 on 2019-10-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191004_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Text'),
        ),
    ]
