# Generated by Django 2.2.13 on 2021-05-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_telegrambot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'verbose_name': '123', 'verbose_name_plural': '321'},
        ),
    ]
