# Generated by Django 2.2.13 on 2021-05-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210506_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'verbose_name': 'Модератор', 'verbose_name_plural': 'Модераторы'},
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='idChat',
            field=models.CharField(max_length=255, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
