# Generated by Django 2.2.13 on 2021-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210506_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('delivery_date', models.DateField(verbose_name='Delivery date')),
                ('delivery_time', models.SmallIntegerField(choices=[(0, '09-10'), (1, '10-11'), (2, '11-12'), (3, '12-13'), (4, '13-14'), (5, '14-15'), (6, '15-16'), (7, '16-17'), (8, '17-18'), (9, '18-18.30')], verbose_name='Delivery time')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('payment', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Card'), (2, 'Online')], verbose_name='Payment method')),
                ('status', models.BooleanField(default=0, verbose_name='Payment confirmed')),
            ],
            options={
                'verbose_name': 'Legal order',
                'verbose_name_plural': 'Legal orders',
            },
        ),
    ]
