# Generated by Django 2.2.13 on 2021-05-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210506_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unp', models.CharField(max_length=30, verbose_name='УНП')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('legalAddress', models.CharField(max_length=50, verbose_name='Юридический адрес')),
                ('addressOrder', models.CharField(max_length=50, verbose_name='Адрес доставки')),
                ('contactPerson', models.CharField(max_length=50, verbose_name='Контактное лицо')),
                ('number', models.CharField(max_length=15, verbose_name='Номер')),
                ('note', models.TextField(max_length=2000, verbose_name='Примечание')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('payment', models.BooleanField(verbose_name='Формат оплаты')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='point',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
