# Generated by Django 2.2.13 on 2021-05-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210515_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalorder',
            options={'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),
    ]
