# Generated by Django 2.2.13 on 2021-05-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210522_0943'),
        ('shop', '0009_legalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorder',
            name='legal_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.LegalUser', verbose_name='legal user'),
            preserve_default=False,
        ),
    ]
