# Generated by Django 2.2.13 on 2021-06-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('shop', '0010_auto_20210609_0720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='CustomOrder',
        ),
    ]
