# Generated by Django 2.2.13 on 2021-05-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('shop', '0010_legalorder_legal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'Small'), ('large', 'Large'), ('none', 'None')], max_length=100, verbose_name='Size')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Pizza', verbose_name='Item')),
                ('order_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.LegalOrder', verbose_name='Legal order')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'abstract': False,
            },
        ),
    ]
