# Generated by Django 2.2.13 on 2021-06-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('shop', '0011_auto_20210609_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Customer'),
            preserve_default=False,
        ),
    ]
