# Generated by Django 2.2.13 on 2021-06-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210609_1118'),
        ('shop', '0012_auto_20210609_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('delivery_date', models.DateField(verbose_name='Delivery date')),
                ('delivery_time', models.SmallIntegerField(choices=[(0, '09-10'), (1, '10-11'), (2, '11-12'), (3, '12-13'), (4, '13-14'), (5, '14-15'), (6, '15-16'), (7, '16-17'), (8, '17-18'), (9, '18-18.30')], verbose_name='Delivery time')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('payment', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Card'), (2, 'Online')], verbose_name='Payment method')),
                ('status', models.BooleanField(default=0, verbose_name='Payment confirmed')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('first_name', models.CharField(max_length=100, verbose_name='Order')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CustomerOrder', verbose_name='Order'),
        ),
        migrations.DeleteModel(
            name='CustomOrder',
        ),
    ]
