# Generated by Django 2.2.13 on 2021-05-24 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210522_0943'),
        ('shop', '0012_remove_legalorder_legal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalorder',
            name='legal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.LegalUser', verbose_name='legal user'),
        ),
    ]
