# Generated by Django 2.2.13 on 2021-07-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_price_name'),
        ('shop', '0015_auto_20210611_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Price'),
        ),
        migrations.AddField(
            model_name='legalorder',
            name='delivery_time',
            field=models.SmallIntegerField(choices=[(0, '09-10'), (1, '10-11'), (2, '11-12'), (3, '12-13'), (4, '13-14'), (5, '14-15'), (6, '15-16'), (7, '16-17'), (8, '17-18'), (9, '18-18.30')], default=0, verbose_name='Delivery time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalorder',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Price'),
        ),
        migrations.DeleteModel(
            name='CompanyOrderItem',
        ),
    ]
