# Generated by Django 2.2.13 on 2021-07-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210718_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='legalorder',
            name='price',
        ),
    ]
