# Generated by Django 2.0 on 2019-09-19 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('content', models.CharField(max_length=100, verbose_name='Content')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('category', models.ManyToManyField(to='catalog.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('disc_percent', models.IntegerField(blank=True, null=True, verbose_name='Discount percent')),
                ('disc_value', models.IntegerField(blank=True, null=True, verbose_name='Discount value')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('expiration_date', models.DateField(blank=True, default=None, null=True, verbose_name='Expiration date')),
            ],
            options={
                'verbose_name_plural': 'Promo code groups',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('small', 'Small'), ('large', 'Large'), ('none', 'None')], max_length=20, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.Pizza', verbose_name='Pizza')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='catalog.PromoCodeGroup'),
        ),
    ]
