# Generated by Django 2.2.13 on 2021-07-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price')),
                ('product', models.ManyToManyField(to='catalog.Pizza')),
            ],
        ),
    ]
