# Generated by Django 2.2.13 on 2021-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(default='test', max_length=15, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
