# Generated by Django 2.2.13 on 2021-07-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_price_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
    ]
