# Generated by Django 2.2.5 on 2019-09-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20190919_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('5', 'Friday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('7', 'Sunday'), ('4', 'Thursday'), ('6', 'Saturday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
