# Generated by Django 2.2.5 on 2019-10-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20191001_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('5', 'Friday'), ('3', 'Wednesday'), ('7', 'Sunday'), ('2', 'Tuesday'), ('4', 'Thursday'), ('6', 'Saturday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
