# Generated by Django 2.2.5 on 2019-10-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20191001_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('4', 'Thursday'), ('7', 'Sunday'), ('2', 'Tuesday'), ('1', 'Monday'), ('6', 'Saturday'), ('5', 'Friday'), ('3', 'Wednesday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
