# Generated by Django 2.2.5 on 2019-10-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20191004_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('7', 'Sunday'), ('3', 'Wednesday'), ('6', 'Saturday'), ('4', 'Thursday'), ('2', 'Tuesday'), ('1', 'Monday'), ('5', 'Friday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
