# Generated by Django 2.2.5 on 2019-10-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20191008_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('5', 'Friday'), ('2', 'Tuesday'), ('6', 'Saturday'), ('7', 'Sunday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('1', 'Monday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
