# Generated by Django 2.2.5 on 2019-10-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20191011_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('7', 'Sunday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('1', 'Monday'), ('6', 'Saturday'), ('5', 'Friday'), ('4', 'Thursday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
