# Generated by Django 2.2.5 on 2019-10-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20191014_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('5', 'Friday'), ('7', 'Sunday'), ('3', 'Wednesday'), ('2', 'Tuesday'), ('6', 'Saturday'), ('1', 'Monday'), ('4', 'Thursday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
