# Generated by Django 2.2.5 on 2019-10-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20191014_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='date',
            name='message',
        ),
        migrations.RemoveField(
            model_name='date',
            name='weekday',
        ),
    ]
